name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        ros_distro: [humble, rolling] # iron not supported yet by action-ros-ci
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
            ros_distribution: humble
            ros_version: 2
          # # Iron Irwini (May 2023 - November 2024)
          # - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-iron-ros-base-latest
          #   ros_distribution: iron
          #   ros_version: 2
          # Rolling Ridley  (June 2020 - Present)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-rolling-ros-base-latest
            ros_distribution: rolling
            ros_version: 2
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ros_distribution == 'rolling' }}
    container:
      image: ${{ matrix.docker_image }}
    steps:
    - uses: actions/checkout@v4

    - name: Search packages in this repository
      id: list_packages
      run: |
        echo ::set-output name=package_list::$(colcon list --names-only)

    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: ${{ matrix.ros_distro }}

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@1.78
      with:
        components: clippy, rustfmt

    - name: build and test
      uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: ${{ steps.list_packages.outputs.package_list }}
        target-ros2-distro: ${{ matrix.ros_distro }}
        vcs-repo-file-url: rmw_libp2p_${{ matrix.ros_distro }}.repos
